location_tag: ['local-ubuntu-159']
project: 'jinsob/SVFIN'
api_token: 'eyJhcGlfYWRkcmVzcyI6Imh0dHBzOi8vYXBwLm5lcHR1bmUuYWkiLCJhcGlfdXJsIjoiaHR0cHM6Ly9hcHAubmVwdHVuZS5haSIsImFwaV9rZXkiOiJjYjQzYTdhNi00MmY5LTQ1ZDUtODRmZi1iODU3NzU0MGQxZGEifQ=='